server:
  port: 9090

# mysql
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/library
#    username: admin
#    password: admin123

# openGauss
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.56.113:5432/library
    username: idea
    password: idea@123

logging:
  level:
    root: info
    mapper: info
    com.baomidou.mybatisplus: info
  config: classpath:logback-spring.xml

mybatis:
  mapper-locations: classpath:mapper/*

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl